# docker-compose.yml

services:
  backend:
    build: ./backend
    container_name: rumoclaro-backend-container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # CORREÇÃO: Use um volume nomeado para o diretório de dados.
      # Isto irá persistir o ficheiro da base de dados sem substituir o country.json.
      - rumoclaro_data:/app/data

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    container_name: rumoclaro-caddy-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    depends_on:
      - backend

# Defina os volumes nomeados no nível superior do ficheiro.
volumes:
  rumoclaro_data: # Volume para persistir a base de dados do backend.
  caddy_data: